TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devgemorc.db
DATA += devgemorc.proto

#=======================================
include $(TOP)/configure/RULES
